@startuml
left to right direction

rectangle "TPM" as TPM {
  [1. Extend PCR]
  [5. seal blob with policy]
}

rectangle "blob partition" as BLOB {
  [3. Unsealed blob]
}

rectangle "U-Boot, Kernel" as MEASUREMENTS {
  [measurements]
}

rectangle "Cominit" as COMINIT {
  [0. public verification key of rootfs metadata]
  [2. Mount blob partition]
  [4. create passphrase and add to blob]
  [6. Add passphrase from blob to user keyring]
  [7. cryptsetup creates and opens LUKS volume with passphrase]
  [8. switch to rootfs]
}

rectangle "Crinit" as Crinit {
 [9. Proceed boot]
}

[0. public verification key of rootfs metadata] --> [1. Extend PCR]
[measurements] --> [1. Extend PCR]
[1. Extend PCR] --> [2. Mount blob partition]
[2. Mount blob partition] --> [3. Unsealed blob]
[3. Unsealed blob] --> [4. create passphrase and add to blob]
[4. create passphrase and add to blob] --> [5. seal blob with policy]
[5. seal blob with policy] --> [6. Add passphrase from blob to user keyring]
[6. Add passphrase from blob to user keyring] --> [7. cryptsetup creates and opens LUKS volume with passphrase]
[7. cryptsetup creates and opens LUKS volume with passphrase] --> [8. switch to rootfs]
[8. switch to rootfs] --> [9. Proceed boot]

@enduml
